(in-package #:wasmgen/tests)

(defun run-tests ()
  (when (null +tests+) (error "No tests added"))
  (ansi:format-ansi T `((:fg :green "== WASMGEN TESTS ==")
                        ,(format nil "~%Running ~A test(s).~%" (length +tests+))))
  (let ((ok-count 0)
        (fail-count 0)
        (error-count 0))
    (dolist (test +tests+)
      (let ((result
              (handler-case (eval-test test)
                (error (e) (list :error e)))))
        (case (car result)
          (:ok
           (incf ok-count)
           (ansi:format-ansi T `((:fg :green "OK: ")
                                 (:st :bold ,(test-name test))
                                 ,(string #\Newline))))
          (:error
           (incf error-count)
           (ansi:format-ansi T `((:fg :red "ERROR: ")
                                 (:st :bold ,(test-name test))
                                 ,(format nil " ~A~%" (cdr result)))))
          (T
           (incf fail-count)
           (ansi:format-ansi T `((:fg :yellow ,(format nil "~A: " (car result)))
                                 (:st :bold :fg :red ,(test-name test))
                                 ,(format nil " ~A~%" (cdr result))))))))
    (format T "Success: ~A, Failures: ~A, Errors: ~A~%" ok-count fail-count error-count)))
