(in-package #:wasmgen)

(defparameter +section-id/custom+         0)
(defparameter +section-id/type+           1)
(defparameter +section-id/import+         2)
(defparameter +section-id/function+       3)
(defparameter +section-id/table+          4)
(defparameter +section-id/memory+         5)
(defparameter +section-id/global+         6)
(defparameter +section-id/export+         7)
(defparameter +section-id/start+          8)
(defparameter +section-id/element+        9)
(defparameter +section-id/code+          10)
(defparameter +section-id/data+          11)
(defparameter +section-id/data-count+    12)
(defparameter +section-id/tag+           13)

(defparameter +type/array+   #x5e)
(defparameter +type/struct+  #x5f)
(defparameter +type/func+    #x60)
(defparameter +type/f64+     #x7c)
(defparameter +type/f32+     #x7d)
(defparameter +type/i64+     #x7e)
(defparameter +type/i32+     #x7f)

